name: Math2Word
on:
  push:
    paths:
      - 'input/**'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          pip install -q -U google-generativeai

      - name: Run
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py

      - name: Save Word
        uses: actions/upload-artifact@v4
        with:
          name: Ket_qua_Word
          path: "*.docx"
