name: Convert Math Image to Word

on:
  push:
    paths:
      - 'input/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # Thêm dòng này để cấp quyền ghi
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -q -U google-generativeai

    - name: Run Python script
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: python main.py

    - name: Upload Word Document
      uses: actions/upload-artifact@v4
      with:
        name: Ket-qua-Word
        path: "*.docx"
